#define KEY_CLEAR          00
#define KEY_ERRORROLLOVER  01
#define KEY_POSTFAIL       02
#define KEY_ERRORUNDEFINED 03
#define KEY_A              04
#define KEY_B              05
#define KEY_C              06
#define KEY_D              07
#define KEY_E              08
#define KEY_F              09
#define KEY_G              0A
#define KEY_H              0B
#define KEY_I              0C
#define KEY_J              0D
#define KEY_K              0E
#define KEY_L              0F
#define KEY_M              10
#define KEY_N              11
#define KEY_O              12
#define KEY_P              13
#define KEY_Q              14
#define KEY_R              15
#define KEY_S              16
#define KEY_T              17
#define KEY_U              18
#define KEY_V              1A
#define KEY_W              1A
#define KEY_X              1B
#define KEY_Y              1C
#define KEY_Z              1D
#define KEY_1              1E
#define KEY_2              1F
#define KEY_3              20
#define KEY_4              21
#define KEY_5              22
#define KEY_6              23
#define KEY_7              24
#define KEY_8              25
#define KEY_9              26
#define KEY_0              27
#define KEY_RETURN         28
#define KEY_ESCAPE         29
#define KEY_DELETE         2A
#define KEY_TAB            2B
#define KEY_SPACEBAR       2C
#define KEY_DASH           2D
#define KEY_EQUAL          2E
#define KEY_LBRACKET       2F
#define KEY_RBRACKET       30
#define KEY_BSLASH         31
#define KEY_NON-US-HASH    32
#define KEY_SEMICOLON      33
#define KEY_APOSTROPHE     34
#define KEY_TILDE          35
#define KEY_COMMA          36
#define KEY_PERIOD         37
#define KEY_SLASH          38
#define KEY_CAPS           39
#define KEY_F1             3A
#define KEY_F2             3B
#define KEY_F3             3C
#define KEY_F4             3D
#define KEY_F5             3E
#define KEY_F6             3F
#define KEY_F7             40
#define KEY_F8             41
#define KEY_F9             42
#define KEY_F10            43
#define KEY_F11            44
#define KEY_F12            45
#define KEY_PRINTSCREEN    46
#define KEY_SCROLL-LOCK    47
#define KEY_PAUSE          48
#define KEY_INSERT         49
#define KEY_HOME           4A
#define KEY_PAGEUP         4B
#define KEY_DELETE-FORWARD 4C
#define KEY_END            4D
#define KEY_PAGEDOWN       4E
#define KEY_RIGHTARROW     4F
#define KEY_LEFTARROW      50
#define KEY_DOWNARROW      51
#define KEY_UPARROW        52
#define KEYPAD_NUM-LOCK    53
#define KEYPAD_SLASH       54
#define KEYPAD_STAR        55
#define KEYPAD_DASH        56
#define KEYPAD_PLUS        57
#define KEYPAD_ENTER       58
#define KEYPAD_1           59
#define KEYPAD_2           5A
#define KEYPAD_3           5B
#define KEYPAD_4           5C
#define KEYPAD_5           5D
#define KEYPAD_6           5E
#define KEYPAD_7           5F
#define KEYPAD_8           60
#define KEYPAD_9           61
#define KEYPAD_0           62
#define KEYPAD_PERIOD      63
#define KEY_NON-US-BSLASH  64
#define KEY_APPLICATION    65
#define KEY_POWER          66
#define KEYPAD_EQUAL       67
#define KEY_F13            68
#define KEY_F14            69
#define KEY_F15            6A
#define KEY_F16            6B
#define KEY_F17            6C
#define KEY_F18            6D
#define KEY_F19            6E
#define KEY_F20            6F
#define KEY_F21            70
#define KEY_F22            71
#define KEY_F23            72
#define KEY_F24            73
#define KEY_EXECUTE        74
#define KEY_HELP           75
#define KEY_MENU           76
#define KEY_SELECT         77
#define KEY_STOP           78
#define KEY_AGAIN          79
#define KEY_UNDO           7A
#define KEY_CUT            7B
#define KEY_COPY           7C
#define KEY_PASTE          7D
#define KEY_FIND           7E
#define KEY_MUTE           7F
#define KEY_VOLUME-UP      80
#define KEY_VOLUME-DOWN    81
#define KEY_LOCK-CAPS-LOCK 82
#define KEY_LOCK-NUM-LOCK  83
#define KEY_LOCK-SCRL-LOCK 84
#define KEYPAD_COMMA       85
#define KEYPAD_EQUAL       86
#define KEY_INTERNATIONAL1 87
#define KEY_INTERNATIONAL2 88
#define KEY_INTERNATIONAL3 89
#define KEY_INTERNATIONAL4 8A
#define KEY_INTERNATIONAL5 8B
#define KEY_INTERNATIONAL6 8C
#define KEY_INTERNATIONAL7 8D
#define KEY_INTERNATIONAL8 8E
#define KEY_INTERNATIONAL9 8F
#define KEY_LANG1          90
#define KEY_LANG2          91
#define KEY_LANG3          92
#define KEY_LANG4          93
#define KEY_LANG5          94
#define KEY_LANG6          95
#define KEY_LANG7          96
#define KEY_LANG8          97
#define KEY_LANG9          98
#define KEY_ALT-ERASE      99
#define KEY_SYSREQ         9A
#define KEY_CANCEL         9B
#define KEY_CLEAR          9C
#define KEY_PRIOR          9D
#define KEY_RETURN         9E
#define KEY_SEPARATOR      9F
#define KEY_OUT            A0
#define KEY_OPER           A1
#define KEY_CLEAR          A2
#define KEY_CRSEL          A3
#define KEY_EXSEL          A4
#define KEY_LEFT-CONTROL   E0
#define KEY_LEFT-SHIFT     E1
#define KEY_LEFT-ALT       E2
#define KEY_LEFT-GUI       E3
#define KEY_RIGHT-CONTROL  E4
#define KEY_RIGHT-SHIFT    E5
#define KEY_RIGHT-ALT      E6
#define KEY_RIGHT-GUI      E7
